<?php
// create_character.php - Dynamic Character Creation
require_once 'discord.php';
require_once 'auth.php';
$user_id = $current_user['id']; // $current_user is automatically generated by auth.php

$user_id = $_SESSION['user_id'];
$success = '';
$error = '';

// 1. Fetch the blueprint for 'characters'
$schema_stmt = $pdo->prepare("SELECT * FROM system_form_schemas WHERE form_target = 'characters' ORDER BY tab_name ASC, sort_order ASC");
$schema_stmt->execute();
$schema_fields = $schema_stmt->fetchAll(PDO::FETCH_ASSOC);

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $char_name = trim($_POST['char_name']);
    $dept_id = $_POST['department_id'] ?: null;
    $pos_id = $_POST['position_id'] ?: null;

    // Extract dynamic fields based on the blueprint
    $dynamic_data = [];
    foreach ($schema_fields as $field) {
        $key = $field['field_key'];
        if (isset($_POST[$key])) {
            $dynamic_data[$key] = trim($_POST[$key]);
        }
    }
    
    // Convert array to JSON
    $json_data = json_encode($dynamic_data);

    try {
        $stmt = $pdo->prepare("INSERT INTO characters (user_id, name, department_id, position_id, dynamic_data, is_active) VALUES (?, ?, ?, ?, ?, 1)");
        $stmt->execute([$user_id, $char_name, $dept_id, $pos_id, $json_data]);
        $success = "Character successfully created and added to the roster!";
        
        // --- ADD THIS BLOCK ---
        $msg = "**{$char_name}** has just been cleared for active duty and added to the roster.";
        send_discord_webhook($pdo, "New Character Created", $msg, "3498db"); // Blue embed
        // ----------------------
        
    } catch (PDOException $e) {
        $error = "An error occurred while saving the character.";
    }
}

// Fetch Departments and Positions for the static assignment dropdowns
$departments = $pdo->query("SELECT id, name FROM departments ORDER BY sort_order ASC")->fetchAll();
$positions_raw = $pdo->query("SELECT id, department_id, name FROM positions ORDER BY sort_order ASC")->fetchAll();
$positions_json = json_encode($positions_raw);

// Group dynamic fields by tab for rendering
$dynamic_tabs = [];
foreach ($schema_fields as $field) {
    $dynamic_tabs[$field['tab_name']][] = $field;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Character - MOWS</title>
    <style>
        body { font-family: Arial, sans-serif; background-color: #f4f4f9; color: #333; padding: 20px; }
        .form-container { max-width: 900px; margin: 0 auto; background: #fff; padding: 0; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); overflow: hidden; }
        .header { background: #2c3e50; color: white; padding: 20px; text-align: center; }
        
        /* Tab Navigation */
        .tab { overflow: hidden; background-color: #e2e8f0; display: flex; flex-wrap: wrap; }
        .tab button { background-color: inherit; border: none; outline: none; cursor: pointer; padding: 14px 16px; transition: 0.3s; font-size: 15px; flex: 1; font-weight: bold; color: #555; white-space: nowrap; }
        .tab button:hover { background-color: #cbd5e1; }
        .tab button.active { background-color: #fff; color: #18bc9c; border-top: 3px solid #18bc9c; }
        
        /* Tab Content */
        .tabcontent { display: none; padding: 20px; border-top: none; }
        .form-group { margin-bottom: 15px; }
        label { display: block; margin-bottom: 5px; font-weight: bold; color: #2c3e50; }
        input[type="text"], select, textarea { width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; }
        textarea { height: 120px; resize: vertical; }
        .row { display: flex; gap: 15px; }
        .row .form-group { flex: 1; }
        
        .submit-bar { background: #f8f9fa; padding: 20px; text-align: right; border-top: 1px solid #eee; }
        button.save-btn { background: #18bc9c; color: white; padding: 12px 25px; border: none; border-radius: 4px; font-size: 16px; font-weight: bold; cursor: pointer; }
        button.save-btn:hover { background: #128f76; }
        
        .message { padding: 15px; margin: 20px; border-radius: 4px; font-weight: bold; }
        .success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .error { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        a.back-btn { color: #fff; text-decoration: none; font-size: 14px; position: absolute; margin-left: -400px; margin-top: 5px; }
    </style>
</head>
<body>

<div class="form-container">
    <div class="header">
        <a href="index.php" class="back-btn">&larr; Dashboard</a>
        <h2 style="margin: 0;">Service Record Entry</h2>
    </div>

    <?php if ($success): ?><div class="message success"><?php echo htmlspecialchars($success); ?></div><?php endif; ?>
    <?php if ($error): ?><div class="message error"><?php echo htmlspecialchars($error); ?></div><?php endif; ?>

    <!-- Render Tab Buttons -->
    <div class="tab">
        <button class="tablinks active" type="button" onclick="openTab(event, 'tab_core_assignment')">Assignment</button>
        <?php foreach (array_keys($dynamic_tabs) as $index => $tab_name): ?>
            <!-- Create a safe ID for the tab content div -->
            <?php $safe_id = 'tab_' . preg_replace('/[^a-zA-Z0-9]/', '_', $tab_name); ?>
            <button class="tablinks" type="button" onclick="openTab(event, '<?php echo $safe_id; ?>')">
                <?php echo htmlspecialchars($tab_name); ?>
            </button>
        <?php endforeach; ?>
    </div>

    <form action="create_character.php" method="POST">
        
        <!-- Core Data Tab (Always present for logic routing) -->
        <div id="tab_core_assignment" class="tabcontent" style="display: block;">
            <div class="form-group">
                <label>Character Full Name</label>
                <input type="text" name="char_name" required>
            </div>
            <div class="row">
                <div class="form-group">
                    <label>Department</label>
                    <select name="department_id" id="dept_select" onchange="updatePositions()" required>
                        <option value="">-- Select Department --</option>
                        <?php foreach ($departments as $dept): ?>
                            <option value="<?php echo $dept['id']; ?>"><?php echo htmlspecialchars($dept['name']); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label>Position</label>
                    <select name="position_id" id="pos_select" required>
                        <option value="">-- Select Position --</option>
                    </select>
                </div>
            </div>
        </div>

        <!-- Dynamic Data Tabs -->
        <?php foreach ($dynamic_tabs as $tab_name => $fields): ?>
            <?php $safe_id = 'tab_' . preg_replace('/[^a-zA-Z0-9]/', '_', $tab_name); ?>
            <div id="<?php echo $safe_id; ?>" class="tabcontent">
                <?php foreach ($fields as $field): ?>
                    <div class="form-group">
                        <label><?php echo htmlspecialchars($field['field_label']); ?></label>
                        <?php if ($field['field_type'] === 'textarea'): ?>
                            <textarea name="<?php echo htmlspecialchars($field['field_key']); ?>"></textarea>
                        <?php else: ?>
                            <input type="text" name="<?php echo htmlspecialchars($field['field_key']); ?>">
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>

        <div class="submit-bar">
            <button type="submit" class="save-btn">Save Character Record</button>
        </div>
    </form>
</div>

<script>
    // Tab Switching Logic
    function openTab(evt, tabName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(tabName).style.display = "block";
        evt.currentTarget.className += " active";
    }

    // Dynamic Position Dropdown Logic
    const positions = <?php echo $positions_json; ?>;
    function updatePositions() {
        const deptSelect = document.getElementById('dept_select');
        const posSelect = document.getElementById('pos_select');
        const selectedDept = deptSelect.value;
        
        posSelect.innerHTML = '<option value="">-- Select Position --</option>';
        
        positions.forEach(pos => {
            if (pos.department_id == selectedDept) {
                const option = document.createElement('option');
                option.value = pos.id;
                option.textContent = pos.name;
                posSelect.appendChild(option);
            }
        });
    }
</script>

</body>
</html>