<?php
// edit_character.php - Dynamic Character Editor (With Avatar Upload)
require_once 'auth.php';
$user_id = $current_user['id']; // $current_user is automatically generated by auth.php

$success = '';
$error = '';
$char_id = isset($_GET['id']) ? (int)$_GET['id'] : 0;

if (!$char_id) die("Error: No character ID specified.");

$stmt = $pdo->prepare("SELECT * FROM characters WHERE id = ?");
$stmt->execute([$char_id]);
$character = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$character) die("Error: Character not found.");

$is_admin = in_array($_SESSION['role'], ['admin', 'system_admin']);
if ($character['user_id'] !== $_SESSION['user_id'] && !$is_admin) {
    die("Access Denied: You do not have permission to edit this character.");
}

$schema_stmt = $pdo->prepare("SELECT * FROM system_form_schemas WHERE form_target = 'characters' ORDER BY tab_name ASC, sort_order ASC");
$schema_stmt->execute();
$schema_fields = $schema_stmt->fetchAll(PDO::FETCH_ASSOC);

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $char_name = trim($_POST['char_name']);
    $dept_id = $_POST['department_id'] ?: null;
    $pos_id = $_POST['position_id'] ?: null;
    $avatar = $character['avatar']; // Default to existing

    // Handle Image Upload
    if (isset($_FILES['avatar_file']) && $_FILES['avatar_file']['error'] === UPLOAD_ERR_OK) {
        $allowed_exts = ['jpg', 'jpeg', 'png', 'gif'];
        $ext = strtolower(pathinfo($_FILES['avatar_file']['name'], PATHINFO_EXTENSION));
        
        if (in_array($ext, $allowed_exts)) {
            $new_avatar = uniqid('av_') . '.' . $ext;
            $dest = 'uploads/avatars/' . $new_avatar;
            if (move_uploaded_file($_FILES['avatar_file']['tmp_name'], $dest)) {
                $avatar = $new_avatar;
            }
        } else {
            $error = "Invalid image format. Only JPG, PNG, and GIF are allowed.";
        }
    }

    $dynamic_data = [];
    foreach ($schema_fields as $field) {
        $key = $field['field_key'];
        if (isset($_POST[$key])) $dynamic_data[$key] = trim($_POST[$key]);
    }
    $json_data = json_encode($dynamic_data);

    if (!$error) {
        try {
            $update_stmt = $pdo->prepare("UPDATE characters SET name = ?, department_id = ?, position_id = ?, avatar = ?, dynamic_data = ? WHERE id = ?");
            $update_stmt->execute([$char_name, $dept_id, $pos_id, $avatar, $json_data, $char_id]);
            $success = "Service Record updated successfully!";
            
            $stmt->execute([$char_id]);
            $character = $stmt->fetch(PDO::FETCH_ASSOC);
        } catch (PDOException $e) {
            $error = "An error occurred while updating the character.";
        }
    }
}

$existing_dynamic_data = json_decode($character['dynamic_data'], true) ?: [];
$departments = $pdo->query("SELECT id, name FROM departments ORDER BY sort_order ASC")->fetchAll();
$positions_json = json_encode($pdo->query("SELECT id, department_id, name FROM positions ORDER BY sort_order ASC")->fetchAll());

$dynamic_tabs = [];
foreach ($schema_fields as $field) {
    $dynamic_tabs[$field['tab_name']][] = $field;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit <?php echo htmlspecialchars($character['name']); ?></title>
    <style>
        /* Keeping your exact previous CSS styles here for brevity */
        body { font-family: Arial, sans-serif; background-color: #f4f4f9; color: #333; padding: 20px; }
        .form-container { max-width: 900px; margin: 0 auto; background: #fff; padding: 0; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); overflow: hidden; }
        .header { background: #2c3e50; color: white; padding: 20px; text-align: center; }
        .tab { overflow: hidden; background-color: #e2e8f0; display: flex; flex-wrap: wrap; }
        .tab button { background-color: inherit; border: none; outline: none; cursor: pointer; padding: 14px 16px; transition: 0.3s; font-size: 15px; flex: 1; font-weight: bold; color: #555; white-space: nowrap; }
        .tab button:hover { background-color: #cbd5e1; }
        .tab button.active { background-color: #fff; color: #18bc9c; border-top: 3px solid #18bc9c; }
        .tabcontent { display: none; padding: 20px; border-top: none; }
        .form-group { margin-bottom: 15px; }
        label { display: block; margin-bottom: 5px; font-weight: bold; color: #2c3e50; }
        input[type="text"], input[type="file"], select, textarea { width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; }
        textarea { height: 120px; resize: vertical; }
        .row { display: flex; gap: 15px; align-items: center; }
        .row .form-group { flex: 1; }
        .submit-bar { background: #f8f9fa; padding: 20px; text-align: right; border-top: 1px solid #eee; display: flex; justify-content: space-between; align-items: center; }
        button.save-btn { background: #18bc9c; color: white; padding: 12px 25px; border: none; border-radius: 4px; font-weight: bold; cursor: pointer; }
        button.save-btn:hover { background: #128f76; }
        .message { padding: 15px; margin: 20px; border-radius: 4px; font-weight: bold; }
        .success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .error { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
        a.back-btn, a.view-btn { color: #fff; text-decoration: none; font-size: 14px; position: absolute; margin-top: 5px; }
        a.back-btn { margin-left: -400px; }
        a.view-btn { margin-left: 300px; background: rgba(255,255,255,0.2); padding: 5px 10px; border-radius: 4px; }
    </style>
</head>
<body>

<div class="form-container">
    <div class="header">
        <a href="index.php" class="back-btn">&larr; Dashboard</a>
        <h2 style="margin: 0;">Edit Service Record</h2>
        <a href="character_profile.php?id=<?php echo $char_id; ?>" class="view-btn">View Public Profile &rarr;</a>
    </div>

    <?php if ($success): ?><div class="message success"><?php echo htmlspecialchars($success); ?></div><?php endif; ?>
    <?php if ($error): ?><div class="message error"><?php echo htmlspecialchars($error); ?></div><?php endif; ?>

    <div class="tab">
        <button class="tablinks active" type="button" onclick="openTab(event, 'tab_core_assignment')">Assignment & Avatar</button>
        <?php foreach (array_keys($dynamic_tabs) as $index => $tab_name): ?>
            <?php $safe_id = 'tab_' . preg_replace('/[^a-zA-Z0-9]/', '_', $tab_name); ?>
            <button class="tablinks" type="button" onclick="openTab(event, '<?php echo $safe_id; ?>')"><?php echo htmlspecialchars($tab_name); ?></button>
        <?php endforeach; ?>
    </div>

    <!-- enctype attribute is mandatory for file uploads -->
    <form action="edit_character.php?id=<?php echo $char_id; ?>" method="POST" enctype="multipart/form-data">
        
        <div id="tab_core_assignment" class="tabcontent" style="display: block;">
            <div class="row">
                <div class="form-group" style="flex: 0 0 120px; text-align: center;">
                    <img src="uploads/avatars/<?php echo htmlspecialchars($character['avatar']); ?>" alt="Avatar" style="width: 120px; height: 120px; object-fit: cover; border-radius: 8px; border: 2px solid #ccc;">
                </div>
                <div class="form-group">
                    <label>Upload New Avatar (Square ratio recommended)</label>
                    <input type="file" name="avatar_file" accept="image/png, image/jpeg, image/gif">
                </div>
            </div>

            <div class="form-group">
                <label>Character Full Name</label>
                <input type="text" name="char_name" value="<?php echo htmlspecialchars($character['name']); ?>" required>
            </div>
            <div class="row">
                <div class="form-group">
                    <label>Department</label>
                    <select name="department_id" id="dept_select" onchange="updatePositions()" required>
                        <option value="">-- Select Department --</option>
                        <?php foreach ($departments as $dept): ?>
                            <option value="<?php echo $dept['id']; ?>" <?php echo ($character['department_id'] == $dept['id']) ? 'selected' : ''; ?>><?php echo htmlspecialchars($dept['name']); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label>Position</label>
                    <select name="position_id" id="pos_select" required></select>
                </div>
            </div>
        </div>

        <?php foreach ($dynamic_tabs as $tab_name => $fields): ?>
            <?php $safe_id = 'tab_' . preg_replace('/[^a-zA-Z0-9]/', '_', $tab_name); ?>
            <div id="<?php echo $safe_id; ?>" class="tabcontent">
                <?php foreach ($fields as $field): ?>
                    <?php 
                        $key = $field['field_key'];
                        $current_value = $existing_dynamic_data[$key] ?? ''; 
                    ?>
                    <div class="form-group">
                        <label><?php echo htmlspecialchars($field['field_label']); ?></label>
                        <?php if ($field['field_type'] === 'textarea'): ?>
                            <textarea name="<?php echo htmlspecialchars($key); ?>"><?php echo htmlspecialchars($current_value); ?></textarea>
                        <?php else: ?>
                            <input type="text" name="<?php echo htmlspecialchars($key); ?>" value="<?php echo htmlspecialchars($current_value); ?>">
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>

        <div class="submit-bar">
            <span><a href="character_profile.php?id=<?php echo $char_id; ?>" style="color: #2c3e50; font-weight: bold; text-decoration: none;">Cancel Changes</a></span>
            <button type="submit" class="save-btn">Save Updates</button>
        </div>
    </form>
</div>

<script>
    function openTab(evt, tabName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) tabcontent[i].style.display = "none";
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) tablinks[i].className = tablinks[i].className.replace(" active", "");
        document.getElementById(tabName).style.display = "block";
        evt.currentTarget.className += " active";
    }

    const positions = <?php echo $positions_json; ?>;
    const currentPosId = <?php echo $character['position_id'] ?: 'null'; ?>;
    
    function updatePositions(selectedPosId = null) {
        const deptSelect = document.getElementById('dept_select');
        const posSelect = document.getElementById('pos_select');
        posSelect.innerHTML = '<option value="">-- Select Position --</option>';
        positions.forEach(pos => {
            if (pos.department_id == deptSelect.value) {
                const option = document.createElement('option');
                option.value = pos.id;
                option.textContent = pos.name;
                if (selectedPosId && pos.id == selectedPosId) option.selected = true;
                posSelect.appendChild(option);
            }
        });
    }
    window.onload = function() { if (document.getElementById('dept_select').value !== "") updatePositions(currentPosId); };
</script>

</body>
</html>