<?php
// pm_inbox.php - Private Messaging Hub
require_once 'auth.php';
$user_id = $current_user['id']; // $current_user is automatically generated by auth.php

// Fetch Received Messages
$inbox_stmt = $pdo->prepare("
    SELECT pm.*, u.username AS sender_name 
    FROM private_messages pm 
    JOIN users u ON pm.sender_id = u.id 
    WHERE pm.receiver_id = ? 
    ORDER BY pm.created_at DESC
");
$inbox_stmt->execute([$user_id]);
$inbox = $inbox_stmt->fetchAll();

// Fetch Sent Messages
$outbox_stmt = $pdo->prepare("
    SELECT pm.*, u.username AS receiver_name 
    FROM private_messages pm 
    JOIN users u ON pm.receiver_id = u.id 
    WHERE pm.sender_id = ? 
    ORDER BY pm.created_at DESC
");
$outbox_stmt->execute([$user_id]);
$outbox = $outbox_stmt->fetchAll();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Private Messages - MOWS</title>
    <style>
        body { font-family: Arial, sans-serif; background: #f4f4f9; padding: 20px; color: #333; }
        .pm-container { max-width: 900px; margin: 0 auto; background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); border-top: 5px solid #2c3e50; }
        .header-bar { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #eee; padding-bottom: 10px; margin-bottom: 20px; }
        h2 { margin: 0; color: #2c3e50; }
        a.btn-primary { background: #18bc9c; color: white; padding: 10px 15px; text-decoration: none; border-radius: 4px; font-weight: bold; }
        a.btn-primary:hover { background: #128f76; }
        a.back-btn { color: #18bc9c; text-decoration: none; font-weight: bold; display: block; margin-bottom: 15px; }
        
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        th, td { padding: 12px; border-bottom: 1px solid #eee; text-align: left; }
        th { background-color: #f8f9fa; color: #555; }
        tr.unread td { font-weight: bold; background-color: #eafaf1; }
        a.subject-link { color: #2c3e50; text-decoration: none; }
        a.subject-link:hover { color: #18bc9c; text-decoration: underline; }
    </style>
</head>
<body>

<div class="pm-container">
    <a href="index.php" class="back-btn">&larr; Back to Dashboard</a>
    
    <div class="header-bar">
        <h2>Message Center</h2>
        <a href="pm_send.php" class="btn-primary">Compose New Message</a>
    </div>

    <h3>Inbox</h3>
    <?php if (empty($inbox)): ?>
        <p style="color: #777;">Your inbox is empty.</p>
    <?php else: ?>
        <table>
            <tr><th>From</th><th>Subject</th><th>Received</th></tr>
            <?php foreach ($inbox as $msg): ?>
                <tr class="<?php echo $msg['is_read'] ? '' : 'unread'; ?>">
                    <td><?php echo htmlspecialchars($msg['sender_name']); ?></td>
                    <td><a href="pm_read.php?id=<?php echo $msg['id']; ?>" class="subject-link"><?php echo htmlspecialchars($msg['subject']); ?></a></td>
                    <td><?php echo date('M j, g:i A', strtotime($msg['created_at'])); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php endif; ?>

    <h3>Outbox</h3>
    <?php if (empty($outbox)): ?>
        <p style="color: #777;">You haven't sent any messages.</p>
    <?php else: ?>
        <table>
            <tr><th>To</th><th>Subject</th><th>Sent</th></tr>
            <?php foreach ($outbox as $msg): ?>
                <tr>
                    <td><?php echo htmlspecialchars($msg['receiver_name']); ?></td>
                    <td><a href="pm_read.php?id=<?php echo $msg['id']; ?>" class="subject-link"><?php echo htmlspecialchars($msg['subject']); ?></a></td>
                    <td><?php echo date('M j, g:i A', strtotime($msg['created_at'])); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php endif; ?>
</div>

</body>
</html>