<?php
// pm_send.php - Compose a Private Message (with Quill)
require_once 'auth.php';
$user_id = $current_user['id']; // $current_user is automatically generated by auth.php
$success = '';
$error = '';

// Handle Reply Pre-filling
$reply_receiver_id = '';
$reply_subject = '';
if (isset($_GET['reply_to'])) {
    $orig_id = (int)$_GET['reply_to'];
    $stmt = $pdo->prepare("SELECT sender_id, subject FROM private_messages WHERE id = ? AND receiver_id = ?");
    $stmt->execute([$orig_id, $user_id]);
    $orig_msg = $stmt->fetch();
    if ($orig_msg) {
        $reply_receiver_id = $orig_msg['sender_id'];
        $reply_subject = (strpos($orig_msg['subject'], 'Re:') === 0) ? $orig_msg['subject'] : 'Re: ' . $orig_msg['subject'];
    }
}

// Handle Form Submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $receiver_id = (int)$_POST['receiver_id'];
    $subject = trim($_POST['subject']);
    $message = trim($_POST['message']);

    if ($receiver_id && $subject && $message && $message !== '<p><br></p>') {
        $stmt = $pdo->prepare("INSERT INTO private_messages (sender_id, receiver_id, subject, message) VALUES (?, ?, ?, ?)");
        $stmt->execute([$user_id, $receiver_id, $subject, $message]);
        $success = "Message sent successfully!";
        $reply_receiver_id = ''; $reply_subject = '';
    } else {
        $error = "All fields are required and the message cannot be empty.";
    }
}

// Fetch user list (excluding the current user)
$users = $pdo->prepare("SELECT id, username FROM users WHERE id != ? ORDER BY username ASC");
$users->execute([$user_id]);
$user_list = $users->fetchAll();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Compose Message - MOWS</title>
    <!-- Include Quill Theme CSS -->
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <style>
        body { font-family: Arial, sans-serif; background: #f4f4f9; padding: 20px; color: #333; }
        .compose-container { max-width: 800px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); border-top: 5px solid #18bc9c; }
        h2 { margin-top: 0; color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }
        .form-group { margin-bottom: 20px; }
        label { display: block; font-weight: bold; margin-bottom: 8px; color: #555; }
        select, input[type="text"] { width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 4px; box-sizing: border-box; font-size: 1rem; }
        
        /* Quill specific overrides */
        #quill-editor { height: 250px; font-family: Arial, sans-serif; font-size: 1rem; }
        .ql-toolbar { background: #f8f9fa; border-radius: 4px 4px 0 0; border-color: #ccc !important; }
        .ql-container { border-radius: 0 0 4px 4px; border-color: #ccc !important; }

        button { padding: 12px 25px; background: #18bc9c; color: white; border: none; border-radius: 4px; font-weight: bold; font-size: 1rem; cursor: pointer; margin-top: 15px; }
        button:hover { background: #128f76; }
        a.cancel-btn { color: #888; text-decoration: none; margin-left: 15px; font-weight: bold; }
        .alert { padding: 15px; border-radius: 4px; margin-bottom: 20px; font-weight: bold; }
        .success { background: #d4edda; color: #155724; border: 1px solid #c3e6cb; }
        .error { background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }
    </style>
</head>
<body>

<div class="compose-container">
    <h2>Compose Message</h2>

    <?php if ($success): ?><div class="alert success"><?php echo htmlspecialchars($success); ?></div><?php endif; ?>
    <?php if ($error): ?><div class="alert error"><?php echo htmlspecialchars($error); ?></div><?php endif; ?>

    <form action="pm_send.php" method="POST" id="pm-form">
        <div class="form-group">
            <label>To:</label>
            <select name="receiver_id" required>
                <option value="">-- Select Recipient --</option>
                <?php foreach ($user_list as $u): ?>
                    <option value="<?php echo $u['id']; ?>" <?php echo ($reply_receiver_id == $u['id']) ? 'selected' : ''; ?>>
                        <?php echo htmlspecialchars($u['username']); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="form-group">
            <label>Subject:</label>
            <input type="text" name="subject" value="<?php echo htmlspecialchars($reply_subject); ?>" required>
        </div>

        <div class="form-group">
            <label>Message:</label>
            <input type="hidden" name="message" id="hidden_content">
            <div id="quill-editor"></div>
        </div>

        <div>
            <button type="submit">Send Message</button>
            <a href="pm_inbox.php" class="cancel-btn">Cancel</a>
        </div>
    </form>
</div>

<!-- Include Quill JS Library -->
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<script>
    var quill = new Quill('#quill-editor', {
        theme: 'snow',
        placeholder: 'Write your message here...',
        modules: {
            toolbar: [
                ['bold', 'italic', 'underline', 'strike'], 
                [{ 'color': [] }, { 'background': [] }],          
                ['blockquote'],
                [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                ['link', 'clean']
            ]
        }
    });

    // Capture the HTML output right before the form submits
    var form = document.getElementById('pm-form');
    form.onsubmit = function() {
        var hiddenInput = document.getElementById('hidden_content');
        hiddenInput.value = quill.root.innerHTML;
    };
</script>

</body>
</html>